services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bpcd
      POSTGRES_PASSWORD: bpcd_pass
      POSTGRES_DB: bpcd_eportfolio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
